# Generated by Django 3.0.7 on 2020-06-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_auto_20200629_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
