# Generated by Django 3.0.7 on 2020-06-29 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_auto_20200629_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
